global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'apex-kv'
    static_configs:
      - targets:
          - 'node1:7001'
          - 'node2:7002'
          - 'node3:7003'
    metrics_path: '/metrics'
    scheme: 'http'
